# Generated by Django 2.2.5 on 2019-11-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления сообщения'),
        ),
    ]
